spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql://localhost:3306/scaletoscale
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  #mail:
    #host: smtp.gmail.com
    #port: 587
    #username: scaletoscale@gmail.com
    #password: khuljaodude9648
    #properties:
      #mail:
        #smtp:
          #auth: true
          #starttls:
            #enable: true

user: scaletoscale@gmail.com
pass: <gmail-pass>
domain: http://localhost:8080/

email:
  format:
    otp: <div style="font-family:Helvetica,Arial,sans-serif;min-width:1000px;overflow:auto;line-height:2"> <div style="margin:50px auto;width:70%;padding:20px 0"> <div style="border-bottom:1px solid #eee"> <a href="" style="font-size:1.4em;color: #00466a;text-decoration:none;font-weight:600">ScaleToScale</a> </div><p style="font-size:1.1em">Hi,</p><p>Thank you for choosing S2S. Use the following OTP to complete your Sign Up procedures. OTP is valid for 5 minutes</p><h2 style="background: #00466a;margin: 0 auto;width: max-content;padding: 0 10px;color: #fff;border-radius: 4px;">{{otp}}</h2> <p style="font-size:0.9em;">Regards,<br/>ScaleToScale</p><hr style="border:none;border-top:1px solid #eee"/> <div style="float:right;padding:8px 0;color:#aaa;font-size:0.8em;line-height:1;font-weight:300"> <p>ScaleToScale</p><p>www.scaletoscale.com</p></div></div></div><div style="font-family: Helvetica,Arial,sans-serif;min-width:1000px;overflow:auto;line-height:2"> <div style="margin:50px auto;width:70%;padding:20px 0"> <div style="border-bottom:1px solid #eee"> <a href="" style="font-size:1.4em;color: #00466a;text-decoration:none;font-weight:600">ScaleToScale</a> </div><p style="font-size:1.1em">Hi,</p><p>Thank you for choosing S2S. Use the following OTP to complete your Sign Up procedures. OTP is valid for 5 minutes</p><h2 style="background: #00466a;margin: 0 auto;width: max-content;padding: 0 10px;color: #fff;border-radius: 4px;">{{otp}}</h2> <p style="font-size:0.9em;">Regards,<br/>ScaleToScale</p><hr style="border:none;border-top:1px solid #eee"/> <div style="float:right;padding:8px 0;color:#aaa;font-size:0.8em;line-height:1;font-weight:300"> <p>ScaleToScale</p><p>www.scaletoscale.com</p></div></div></div>
